# Simple workflow for deploying static content to GitHub Pages
# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Deploy static content to Pages

on:
  workflow_call:
    inputs:
      username:
        type: string
        required: true
    secrets:
      access-token:
        required: true
        
jobs:
  pass-secret:
    runs-on: ubuntu-latest
    steps:
      - name: Some secret
        run: |
          echo This is some secret ${{ secret.access-token }}. THis is some input ${{ inputs.username }}
