name: Hello world
run-name: testing pipeline ${{ github.run_number }}
on: [push]

jobs:
  hello-world:
    environment: master
    runs-on: ubuntu-latest
    steps:
      - name: Hello world
        run: |
          echo "Hello world ${{ vars.WORLDMSG }}"
          
  hello-world-qa:
    environment: qa
    runs-on: ubuntu-latest
    steps:
      - name: Hello world
        run: |
          echo "Hello world ${{ vars.WORLDMSG }}"
